### ISSUE TITLE
Baseurl

### ISSUE THREAD

**Issue by ghost** [ujpef/latte-view#3]
And for baseurl? How make this work?

**Comment by jlx84** [comment]
Could you be more specific?

Slim's router generates absolute paths (starting with `/`), so there is no need for `<base href="">` tag when you use `{link ...}` macro correctly - see the readme.

For static assets, you can pass "basePath" variable in app middleware:

```
$app->add(function(Request $request, Response $response, $next) {
    $basePath = $request->getUri()->getBasePath();
    $this->view->addParam('basePath', $basePath);
    return $next($request, $response);
});
```

**Comment by ghost** [comment]
Thanks for help! This works for include js and css files!

**Comment by ghost** [comment]
{{ base_url() }} equals twig, but this is exactly i've search!!!!!!!!
